<a href="https://colab.research.google.com/github/sarmi2325/Machine-Learning/blob/main/Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Using Shape, we can find the dimension of the array.
Also, transpose can be done

In [3]:
n1=np.array([[1,2,3],[4,5,6]])
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
n1.shape

(2, 3)

In [9]:
n1.shape = (3,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

Stacking Methods

Vertical Stack

In [12]:
n2=np.array([1,2,3])
n3=np.array([4,5,6])
np.vstack((n2,n3))

array([[1, 2, 3],
       [4, 5, 6]])

Horizontal Stack

In [13]:
n2=np.array([1,2,3])
n3=np.array([4,5,6])
np.hstack((n2,n3))

array([1, 2, 3, 4, 5, 6])

Column Stack

In [14]:
n2=np.array([1,2,3])
n3=np.array([4,5,6])
np.column_stack((n2,n3))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
n1=np.array([1,2,3,4])
n2=np.array([1,4,5,6])
np.intersect1d(n1,n2)

array([1, 4])

In [16]:
n1=np.array([1,2,3,4])
n2=np.array([1,4,5,6])
np.setdiff1d(n1,n2)

array([2, 3])

In [17]:
n1=np.array([1,2,3,4])
n2=np.array([1,4,5,6])
np.setdiff1d(n2,n1)

array([5, 6])