<a href="https://colab.research.google.com/github/sarmi2325/Machine-Learning/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import numpy library np as its alice name

In [1]:
import numpy as np

using array(), we can create one or multi-dimensional array

In [2]:
n1=np.array([1,2,3,4])
n1

array([1, 2, 3, 4])

In [5]:
n2=np.array([[1,2,3],[4,5,6]])
n2

array([[1, 2, 3],
       [4, 5, 6]])

For initializing the array with zeros, ones, range of values, range of values with skip number or random number of given size can be done using numpy

In [7]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
n4=np.ones((5,2))
n4

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
n=np.full((2,5),5)
n

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [9]:
n5=np.arange(1,50)
n5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [10]:
n6=np.arange(1,51,5)
n6

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [11]:
n7=np.random.randint(1,100,7)
n7

array([39, 68, 20, 86, 71, 60, 71])